<template>
  <div><el-button
         v-if="!isDetail"
         type="primary"
         plain
         size="small"
         class="mb10"
         icon="el-icon-plus"
         @click="openForm"
       >添加设备</el-button>
    <el-table
      v-loading="loading"
      :data="list"
      stripe
      :show-overflow-tooltip="true"
      border
    ><el-table-column
      label="设备编号"
      align="center"
      prop="machineryId"
    /><el-table-column
      label="设备名称"
      align="center"
      prop="machineryName"
    /><el-table-column
      label="数量"
      align="center"
      prop="quantity"
      width="100"
    /><el-table-column
      label="备注"
      align="center"
      prop="remark"
    /><el-table-column
      v-if="!isDetail"
      label="操作"
      align="center"
      width="80"
    ><template v-slot="scope"><el-button
      type="text"
      @click="handleDelete(scope.row.id)"
    >删除</el-button></template></el-table-column></el-table>
    <el-dialog
      title="新增设备资源"
      :visible.sync="dialogVisible"
      width="500px"
      append-to-body
    ><el-form
      ref="form"
      v-loading="formLoading"
      :model="formData"
      :rules="formRules"
      label-width="80px"
    ><el-form-item
      label="设备"
      prop="machineryId"
    ><dv-machinery-select
      v-model="formData.machineryId"
      placeholder="请选择设备"
      class="full-width"
    /></el-form-item><el-form-item
      label="数量"
      prop="quantity"
    ><el-input-number
      v-model="formData.quantity"
      :min="1"
      controls-position="right"
      class="full-width"
    /></el-form-item><el-form-item
      label="备注"
      prop="remark"
    ><el-input
      v-model="formData.remark"
      type="textarea"
      placeholder="请输入备注"
    /></el-form-item></el-form><span slot="footer"><el-button
      type="primary"
      :disabled="formLoading"
      @click="submitForm"
    >确 定</el-button><el-button @click="dialogVisible = false">取 消</el-button></span></el-dialog>
  </div>
</template>
<script>
import { MdWorkstationMachineApi } from '@/api/mes/md/workstation/machine'
import DvMachinerySelect from '@/views/mes/dv/machinery/components/DvMachinerySelect.vue'
export default { name: 'WorkstationMachineList', components: { DvMachinerySelect }, props: { workstationId: { type: Number, required: true }, formType: { type: String, required: true }}, data() { return { loading: false, list: [], dialogVisible: false, formLoading: false, formData: this.getDefaultForm(), formRules: { machineryId: [{ required: true, message: '设备不能为空', trigger: 'blur' }], quantity: [{ required: true, message: '数量不能为空', trigger: 'blur' }] }} }, computed: { isDetail() { return this.formType === 'detail' } }, watch: { workstationId: { immediate: true, handler(value) { if (value) this.getList() } }}, methods: { getDefaultForm() { return { id: undefined, workstationId: this.workstationId, machineryId: undefined, quantity: 1, remark: undefined } }, async getList() { this.loading = true; try { this.list = (await MdWorkstationMachineApi.getWorkstationMachineList(this.workstationId)).data } finally { this.loading = false } }, openForm() { this.dialogVisible = true; this.formData = this.getDefaultForm(); this.$nextTick(() => this.$refs.form && this.$refs.form.resetFields()) }, submitForm() { this.$refs.form.validate(async valid => { if (!valid) return; this.formLoading = true; try { await MdWorkstationMachineApi.createWorkstationMachine(this.formData); this.$modal.msgSuccess('新增成功'); this.dialogVisible = false; await this.getList() } finally { this.formLoading = false } }) }, async handleDelete(id) { try { await this.$modal.confirm('是否确认删除设备资源？'); await MdWorkstationMachineApi.deleteWorkstationMachine(id); this.$modal.msgSuccess('删除成功'); await this.getList() } catch (error) { /* 取消删除 */ } } }}
</script>
<style scoped>.mb10 { margin-bottom: 10px; }.full-width { width: 100%; }</style>
